/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class City: Object {

  enum Attributes: String {
    case id = "id" /* Primary Key */
    case country = "country"
    case name = "name"
    case population = "population"
  }

  enum Relationships: String {
    case coord = "coord"
  }

  let id = RealmOptional<Int64>() /* Primary Key */
  @objc dynamic var country: String?
  @objc dynamic var name: String?
  let population = RealmOptional<Int64>()
  @objc dynamic var coord: Coordinate?

  override static func primaryKey() -> String? {
    return "id"
  }

}
