/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class City: Object {

  enum Attributes: String {
    case id = "id"
    case country = "country"
    case name = "name"
    case population = "population"
  }

  enum Relationships: String {
    case coord = "coord"
  }

  var id = RealmOptional<Int64>()
  dynamic var country: String?
  dynamic var name: String?
  var population = RealmOptional<Int64>()
  dynamic var coord: Coordinate?

  override static func primaryKey() -> String? {
    return "id"
  }

}
