/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Coordinate: Object {

  enum Attributes: String {
    case lat = "lat"
    case lon = "lon"
  }

  var lat = RealmOptional<Double>()
  var lon = RealmOptional<Double>()

}
