/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Coordinate: Object {

  enum Attributes: String {
    case lat = "lat"
    case lon = "lon"
  }

  let lat = RealmOptional<Float>()
  let lon = RealmOptional<Float>()

}
