/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class CurrentWeather: Object {

  enum Attributes: String {
    case id = "id" /* Primary Key */
    case base = "base"
    case cod = "cod"
    case dt = "dt"
    case name = "name"
    case visibility = "visibility"
  }

  enum Relationships: String {
    case clouds = "clouds"
    case coord = "coord"
    case main = "main"
    case sys = "sys"
    case weather = "weather"
    case wind = "wind"
  }

  let id = RealmOptional<Int64>() /* Primary Key */
  @objc dynamic var base: String?
  let cod = RealmOptional<Int64>()
  let dt = RealmOptional<Int64>()
  @objc dynamic var name: String?
  let visibility = RealmOptional<Int64>()
  @objc dynamic var clouds: Cloud?
  @objc dynamic var coord: Coordinate?
  @objc dynamic var main: Main?
  @objc dynamic var sys: Sys?
  var weather = List<Weather>()
  @objc dynamic var wind: Wind?

  override static func primaryKey() -> String? {
    return "id"
  }

}
