/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Main: Object {

  enum Attributes: String {
    case grnd_level = "grnd_level"
    case humidity = "humidity"
    case pressure = "pressure"
    case sea_level = "sea_level"
    case temp = "temp"
    case temp_kf = "temp_kf"
    case temp_max = "temp_max"
    case temp_min = "temp_min"
  }

  var grnd_level = RealmOptional<Double>()
  var humidity = RealmOptional<Int16>()
  var pressure = RealmOptional<Double>()
  var sea_level = RealmOptional<Double>()
  var temp = RealmOptional<Double>()
  var temp_kf = RealmOptional<Double>()
  var temp_max = RealmOptional<Double>()
  var temp_min = RealmOptional<Double>()

}
