/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Main: Object {

  enum Attributes: String {
    case grnd_level = "grnd_level"
    case humidity = "humidity"
    case pressure = "pressure"
    case sea_level = "sea_level"
    case temp = "temp"
    case temp_kf = "temp_kf"
    case temp_max = "temp_max"
    case temp_min = "temp_min"
  }

  let grnd_level = RealmOptional<Double>()
  let humidity = RealmOptional<Int16>()
  let pressure = RealmOptional<Double>()
  let sea_level = RealmOptional<Double>()
  let temp = RealmOptional<Double>()
  let temp_kf = RealmOptional<Double>()
  let temp_max = RealmOptional<Double>()
  let temp_min = RealmOptional<Double>()

}
