/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Measure: Object {

  enum Attributes: String {
    case dt = "dt"
    case dt_txt = "dt_txt"
  }

  enum Relationships: String {
    case clouds = "clouds"
    case main = "main"
    case rain = "rain"
    case sys = "sys"
    case weather = "weather"
    case wind = "wind"
  }

  let dt = RealmOptional<Int64>()
  @objc dynamic var dt_txt: String?
  @objc dynamic var clouds: Cloud?
  @objc dynamic var main: Main?
  @objc dynamic var rain: Rain?
  @objc dynamic var sys: Sys?
  var weather = List<Weather>()
  @objc dynamic var wind: Wind?

}
