/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Rain: Object {

  enum Attributes: String {
    case threeHour = "threeHour"
  }

  let threeHour = RealmOptional<Double>()

}
