/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Sys: Object {

  enum Attributes: String {
    case country = "country"
    case id = "id"
    case message = "message"
    case pod = "pod"
    case sunrise = "sunrise"
    case sunset = "sunset"
    case type = "type"
  }

  dynamic var country: String?
  var id = RealmOptional<Int64>()
  var message = RealmOptional<Double>()
  dynamic var pod: String?
  var sunrise = RealmOptional<Int64>()
  var sunset = RealmOptional<Int64>()
  var type = RealmOptional<Int16>()

}
