/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Sys: Object {

  enum Attributes: String {
    case country = "country"
    case id = "id"
    case message = "message"
    case pod = "pod"
    case sunrise = "sunrise"
    case sunset = "sunset"
    case type = "type"
  }

  @objc dynamic var country: String?
  let id = RealmOptional<Int64>()
  let message = RealmOptional<Double>()
  @objc dynamic var pod: String?
  let sunrise = RealmOptional<Int64>()
  let sunset = RealmOptional<Int64>()
  let type = RealmOptional<Int16>()

}
