/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class ThreeHourForecast: Object {

  enum Attributes: String {
    case cod = "cod"
    case cnt = "cnt"
    case message = "message"
  }

  enum Relationships: String {
    case city = "city"
    case list = "list"
  }

  dynamic var cod: String?
  var cnt = RealmOptional<Int64>()
  var message = RealmOptional<Double>()
  dynamic var city: City?
  var list = List<Measure>()

  override static func primaryKey() -> String? {
    return "cod"
  }

}
