/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class ThreeHourForecast: Object {

  enum Attributes: String {
    case cod = "cod" /* Primary Key */
    case cnt = "cnt"
    case message = "message"
  }

  enum Relationships: String {
    case city = "city"
    case list = "list"
  }

  @objc dynamic var cod: String? /* Primary Key */
  let cnt = RealmOptional<Int64>()
  let message = RealmOptional<Double>()
  @objc dynamic var city: City?
  var list = List<Measure>()

  override static func primaryKey() -> String? {
    return "cod"
  }

}
