/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Weather: Object {

  enum Attributes: String {
    case id = "id" /* Primary Key */
    case descriptionn = "descriptionn"
    case icon = "icon"
    case main = "main"
  }

  let id = RealmOptional<Int64>() /* Primary Key */
  @objc dynamic var descriptionn: String?
  @objc dynamic var icon: String?
  @objc dynamic var main: String?

  override static func primaryKey() -> String? {
    return "id"
  }

}
