/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Weather: Object {

  enum Attributes: String {
    case id = "id"
    case descriptionn = "descriptionn"
    case icon = "icon"
    case main = "main"
  }

  var id = RealmOptional<Int64>()
  dynamic var descriptionn: String?
  dynamic var icon: String?
  dynamic var main: String?

  override static func primaryKey() -> String? {
    return "id"
  }

}
