/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Wind: Object {

  enum Attributes: String {
    case deg = "deg"
    case speed = "speed"
  }

  var deg = RealmOptional<Int32>()
  var speed = RealmOptional<Double>()

}
