/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension City: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.id.value <- map["id"]
    self.country <- map["country"]
    self.name <- map["name"]
    self.population.value <- map["population"]

    // MARK: Relationships
    self.coord <- map["coord"]
  }
}
