/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Cloud: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.all.value <- map["all"]
  }
}
