/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Coordinate: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.lat.value <- map["lat"]
    self.lon.value <- map["lon"]
  }
}
