/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension CurrentWeather: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.id.value <- map["id"]
    self.base <- map["base"]
    self.cod.value <- map["cod"]
    self.dt.value <- map["dt"]
    self.name <- map["name"]
    self.visibility.value <- map["visibility"]

    // MARK: Relationships
    self.clouds <- map["clouds"]
    self.coord <- map["coord"]
    self.main <- map["main"]
    self.sys <- map["sys"]
    self.weather <- (map["weather"], ListTransform<Weather>())
    self.wind <- map["wind"]
  }
}
