/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension DailyForecast: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
  }
}
