/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Main: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.grnd_level.value <- map["grnd_level"]
    self.humidity.value <- map["humidity"]
    self.pressure.value <- map["pressure"]
    self.sea_level.value <- map["sea_level"]
    self.temp.value <- map["temp"]
    self.temp_kf.value <- map["temp_kf"]
    self.temp_max.value <- map["temp_max"]
    self.temp_min.value <- map["temp_min"]
  }
}
