/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Measure: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.dt.value <- map["dt"]
    self.dt_txt <- map["dt_txt"]

    // MARK: Relationships
    self.clouds <- map["clouds"]
    self.main <- map["main"]
    self.rain <- map["rain"]
    self.sys <- map["sys"]
    self.weather <- (map["weather"], ListTransform<Weather>())
    self.wind <- map["wind"]
  }
}
