/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Rain: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.threeHour.value <- map["3h"]
  }
}
