/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Sys: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.country <- map["country"]
    self.id.value <- map["id"]
    self.message.value <- map["message"]
    self.pod <- map["pod"]
    self.sunrise.value <- map["sunrise"]
    self.sunset.value <- map["sunset"]
    self.type.value <- map["type"]
  }
}
