/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension ThreeHourForecast: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.cod <- map["cod"]
    self.cnt.value <- map["cnt"]
    self.message.value <- map["message"]

    // MARK: Relationships
    self.city <- map["city"]
    self.list <- (map["list"], ListTransform<Measure>())
  }
}
