/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Weather: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.id.value <- map["id"]
    self.descriptionn <- map["description"]
    self.icon <- map["icon"]
    self.main <- map["main"]
  }
}
