/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Wind: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.deg.value <- map["deg"]
    self.speed.value <- map["speed"]
  }
}
